import type { WorkflowProject } from "@/lib/types/workflow"

interface ExportedStep {
	id: string
	name: string
	description: string
	systemPrompt: string
	model: string
	inputSource: string
	outputKey: string
}

interface WorkflowConfig {
	name: string
	steps: ExportedStep[]
}

/**
 * Export the workflow as a portable JSON config.
 */
export function exportWorkflowConfig(workflow: WorkflowProject): WorkflowConfig {
	return {
		name: workflow.name,
		steps: workflow.steps.map((step) => ({
			id: step.id,
			name: step.name,
			description: step.description,
			systemPrompt: step.bestPrompt || step.systemPrompt,
			model: step.model,
			inputSource: step.inputSource,
			outputKey: step.outputKey,
		})),
	}
}

/**
 * Export the workflow as a self-contained TypeScript SDK file.
 * The generated file uses fetch (no npm dependencies) to call OpenRouter.
 */
export function exportWorkflowSDK(workflow: WorkflowProject): string {
	const config = exportWorkflowConfig(workflow)
	const configJson = JSON.stringify(config, null, 2)

	return `/**
 * Auto-generated workflow SDK: ${escapeForTemplate(workflow.name)}
 * Generated by Prompt Optimizer
 *
 * Usage:
 *   import { runWorkflow } from "./workflow"
 *   const result = await runWorkflow("your input text", "your-openrouter-api-key")
 *   console.log(result.final_output)
 */

const WORKFLOW_CONFIG = ${configJson} as const

interface WorkflowStepResult {
  stepId: string
  stepName: string
  output: string
  model: string
}

interface WorkflowResult {
  steps: WorkflowStepResult[]
  final_output: string
  outputs: Record<string, string>
}

async function callOpenRouter(
  model: string,
  systemPrompt: string,
  userInput: string,
  apiKey: string
): Promise<string> {
  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: \`Bearer \${apiKey}\`,
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userInput },
      ],
    }),
  })

  if (!response.ok) {
    const errorBody = await response.text()
    throw new Error(\`OpenRouter API error (\${response.status}): \${errorBody}\`)
  }

  const data = await response.json()
  return data.choices?.[0]?.message?.content ?? ""
}

export async function runWorkflow(
  input: string,
  apiKey?: string
): Promise<WorkflowResult> {
  const key = apiKey ?? process.env.OPENROUTER_API_KEY
  if (!key) {
    throw new Error("API key required: pass as argument or set OPENROUTER_API_KEY env var")
  }

  const outputs: Record<string, string> = { workflow_input: input }
  const stepResults: WorkflowStepResult[] = []

  for (const step of WORKFLOW_CONFIG.steps) {
    const stepInput = outputs[step.inputSource] ?? input
    const output = await callOpenRouter(step.model, step.systemPrompt, stepInput, key)

    outputs[step.outputKey] = output
    stepResults.push({
      stepId: step.id,
      stepName: step.name,
      output,
      model: step.model,
    })
  }

  const lastStep = WORKFLOW_CONFIG.steps[WORKFLOW_CONFIG.steps.length - 1]
  const finalOutput = outputs[lastStep.outputKey] ?? ""

  return {
    steps: stepResults,
    final_output: finalOutput,
    outputs,
  }
}
`
}

function escapeForTemplate(s: string): string {
	return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$")
}
